### ISSUE TITLE
Cannot send second collection invite

### ISSUE THREAD

**Issue by Mathis-Z** [openHPI/codeharbor#1668] opened 2024-09-18 15:31 UTC
Steps to reproduce:
- send a collection invitation
- delete the invitation message
- send a second collection invitation to the same user for the same collection
=> flash message: "Something went wrong"

**Comment by MrSerth** [comment] 2024-09-19 07:29
This bug might be related to or a duplicate of #1414.

**Closed** 2024-09-24 15:44 UTC
Labels: bug
