### ISSUE TITLE
Quotes in ProFormA Description are escaped

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#1095] opened 2023-11-17 12:16 UTC
Importing a ProFormA task containing quotes in the description generally works. However, those quotes are shown / stored escaped in CodeHarbor:

<img width="1840" alt="Bildschirmfoto 2023-11-17 um 13 15 46" src="https://github.com/openHPI/codeharbor/assets/7300329/b1077cee-fdc2-42eb-8034-8e73f1645771">

The XML just contains regular quotes:

```xml
<description><![CDATA[<p>
Schreiben Sie ein Programm, das "Hello World!" (ohne die Anf&uuml;hrungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String "Hello World!" zur&uuml;ckgibt. Die Klasse soll "HelloWorld" und die Methode soll "greet" hei&szlig;en.
</p>]]></description>
```

Here is a corresponding task: [helloWorld.zip](https://github.com/openHPI/codeharbor/files/13391511/helloWorld.zip)

**Comment by kkoehn** [comment] 2024-02-24 12:36
I tried importing the zip and everything works as expected. Maybe it got fixed by #1104?

**Comment by MrSerth** [comment] 2024-02-24 18:43
I was still able to reproduce the issue. However, since I enabled Markdown formatting for the description, it is only visible when editing the task. Further, I also noticed that the importer adds some new-lines, where the original XML does not include any...

Tested with c632dc57

<img width="1840" alt="Bildschirmfoto 2024-02-24 um 19 39 59" src="https://github.com/openHPI/codeharbor/assets/7300329/7cca002c-c5f0-488b-a10e-e793d3b750fe">
<img width="1580" alt="Bildschirmfoto 2024-02-24 um 19 41 53" src="https://github.com/openHPI/codeharbor/assets/7300329/3e8c4de7-bc66-40e3-9018-717f7dc2c925">

**Comment by kkoehn** [comment] 2024-02-25 14:16
- The cause of the unexpected newlines seems to be coming from the `line_width` option of kramdown which defaults to 72.
  - We could set the `line_width` to a high number to avoid creating linebreaks - I did not find an option to disable them alltogether
- I have not found the concrete source of the double escapes, but it only seems to happen because `html_to_native` is resolving the `<p>`s

**Comment by kkoehn** [comment] 2024-02-26 21:58
I managed to find the cause in the kramdown converter [link](https://github.com/gettalong/kramdown/blob/bd678ecb59f70778fdb3b08bdcd39e2ab7379b45/lib/kramdown/converter/kramdown.rb#L83) but don't see a way to disable it.
It seems to just be the markdown (or kramdown) representation of that string. When converting it back to html it does loose the extra escape.

**Comment by MrSerth** [comment] 2024-02-27 00:33
That's a very valuable finding already, and helped me a lot. Thanks, you definitely helped me understand the problem a little better. Hence, I was doing some debugging on my own:

```rb
3.3.0> html_description_inner = 'Schreiben Sie ein Programm, das "Hello World!" (ohne die Anf&uuml;hrungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String "Hello World!" zur&uuml;ckgibt. Die Klasse soll "HelloWorld" und die Methode soll "greet" hei&szlig;en.'
 => "Schreiben Sie ein Programm, das \"Hello World!\" (ohne die Anf&uuml;hrungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String \"Hello World!\" zur&uuml;ckgibt. Die Klasse soll \"HelloWorld\" und die Methode soll \"greet\" hei&szlig;en." 
3.3.0> puts Kramdown::Document.new("#{html_description_inner}", html_to_native: true, line_width: -1).to_html
<p>Schreiben Sie ein Programm, das “Hello World!” (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String “Hello World!” zurückgibt. Die Klasse soll “HelloWorld” und die Methode soll “greet” heißen.</p>
 => nil 
3.3.0> puts Kramdown::Document.new("<p>#{html_description_inner}</p>", html_to_native: true, line_width: -1).to_html
<p>Schreiben Sie ein Programm, das "Hello World!" (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String "Hello World!" zurückgibt. Die Klasse soll "HelloWorld" und die Methode soll "greet" heißen.</p>
 => nil 
3.3.0 > puts Kramdown::Document.new("<p>#{html_description_inner}</p>", html_to_native: true, line_width: -1).to_kramdown
Schreiben Sie ein Programm, das \"Hello World!\" (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String \"Hello World!\" zurückgibt. Die Klasse soll \"HelloWorld\" und die Methode soll \"greet\" heißen.

 => nil 
3.3.0 > puts Kramdown::Document.new("#{html_description_inner}", html_to_native: true, line_width: -1).to_kramdown
Schreiben Sie ein Programm, das "Hello World!" (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String "Hello World!" zurückgibt. Die Klasse soll "HelloWorld" und die Methode soll "greet" heißen.

 => nil 
3.3.0 > puts Kramdown::Document.new("\"hi\"", line_width: -1).to_html
<p>“hi”</p>
 => nil 
3.3.0 > puts Kramdown::Document.new("\\\"hi\\\"", line_width: -1).to_html
<p>"hi"</p>
 => nil 
```

My relevant findings:

1. If the HTML text is not part of a paragraph (without `</p>`), the resulting HTML has differently shaped quoted (not the standard ones)
2. If the HTML is part of a paragraph (with `<p>`), the resulting HTML reuses the quotes included in the input.
3. In the Kramdown document, the quotes are not escaped when the input was not part of a paragraph.
4. In the Kramdown document, the quotes are escaped when the input was part of a paragraph.
5. Normally, Kramdown will convert regular quotes to "rounded" ones, but not if they are escaped.
6. We can use a negative `line_width` to disable line breaking. 

Long story short, it really seems like some feature ~~(or bug)~~ of Kramdown to handle quotes the current way. Somewhat, it seems logic to me: If the HTML contains regular quotes, the Kramdown representation needs to have them escaped (to reproduce the same result). Otherwise, converting a document back and forth would result in a different rendering. All other changes performed by Markdown (like changing the HTML entities to UTF-8 characters), are invisible in the rendering:

```rb
3.3.0 > input_html = "<p>#{html_description_inner}</p>"
 => "<p>Schreiben Sie ein Programm, das \"Hello World!\" (ohne die Anf&uuml;hrungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String \"Hello World!\" zur&uuml;ckgibt. Die Klasse soll \"HelloWorld\" und die Methode soll \"greet\" hei&szlig;en.</p>" 
3.3.0 > kramdown_conversion = Kramdown::Document.new(input_html, html_to_native: true, line_width: -1).to_kramdown
 => "Schreiben Sie ein Programm, das \\\"Hello World!\\\" (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String \\\"Hello World!\\\" zurückgibt. Die Klasse soll \\\"HelloWorld\\\" und die Methode soll \\\"greet\\\" heißen.\n\n" 
3.3.0 > Kramdown::Document.new(kramdown_conversion).to_html
 => "<p>Schreiben Sie ein Programm, das \"Hello World!\" (ohne die Anführungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String \"Hello World!\" zurückgibt. Die Klasse soll \"HelloWorld\" und die Methode soll \"greet\" heißen.</p>\n\n"
```

That having said, I am still unsure how to continue:

- Do we want to accept the escaped quotes? This makes editing the imported file a bit more trickier, but will ensure that the rendering doesn't change them to a non-programming-compatible form.
- Do we want to ease editing and have the quotes rendered "rounded", which looks nicer, but also makes the resulting text incompatible with programming languages (since you cannot copy this form of quotes)?

**Comment by kkoehn** [comment] 2024-02-29 21:40
Wow, good find with the different quotes; I didn't notice that at all. If we were to consider only Codeharbor, I would lean towards the second option, since nothing here is directly used to program (it has to go through Codeocean or similar platforms first). But then, wouldn't we encounter the same problem in Codeocean? We also use kramdown there to render the description, and now the "pupil" might have to figure out this problem. Therefore, I lean towards the other option and suggest adding a disclaimer for the description field explaining the issue (which could even be conditional and only appear if the description contains a quote). Whoever uses Codeharbor should, in most cases, be more competent in this regard than the end-user of Codeocean.

**Comment by MrSerth** [comment] 2024-03-01 17:24
Yes, we have the same issue on CodeOcean, as shown in the below example:

<img width="995" alt="Bildschirmfoto 2024-03-01 um 17 47 04" src="https://github.com/openHPI/codeharbor/assets/7300329/41cd3b02-79c5-4ba3-92fa-55698fe85a7a">

As you can see, the quotes for the text "Ronja fängt Paco" (or others) are also typographic. At least for the rendering, I found a documented option we can use: `smart_quotes: 'apos,apos,quot,quot'`:

```rb
3.3.0 > test = "Normal, 'Single Quotes', \"Double Quotes\""
 => "Normal, 'Single Quotes', \"Double Quotes\"" 
3.3.0 > puts kramdown_conversion = Kramdown::Document.new(test, html_to_native: true, line_width: -1).to_html
<p>Normal, ‘Single Quotes’, “Double Quotes”</p>
3.3.0 > puts kramdown_conversion = Kramdown::Document.new(test, html_to_native: true, line_width: -1, smart_quotes:'apos,apos,quot,quot').to_html
<p>Normal, 'Single Quotes', "Double Quotes"</p>
```

This, however, doesn't work out for generating the markdown. There, one would need to overwrite `ESCAPED_CHAR_RE`:

```rb
Kramdown::Converter::Kramdown::ESCAPED_CHAR_RE = /(\$\$|[\\*_`\[\]\{|])|^[ ]{0,3}(:)/
```

Of course, the question is what we want.

1. I would suggest to apply the `smart_quotes` option, For our programming use, this makes sense and I would accept the slightly reduced typographic style over the increased possibility to copy and paste.
2. One could either use a monkey patch for the regex, or leave it as it is. Maybe a monkey patch, to avoid those undesired changes?

Once we apply the changes in CodeHarbor, I would suggest performing similar changes in CodeOcean (as part of this ticket).

**Closed** 2024-03-27 15:51 UTC
Labels: bug, data exchange
